// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-itzpWtlL2X8_GQinF_DzvvIeoOamHGg',
    appId: '1:407480712095:web:ea6c93791c0b24823c5baa',
    messagingSenderId: '407480712095',
    projectId: 'captura-lens-6d2a3',
    authDomain: 'captura-lens-6d2a3.firebaseapp.com',
    storageBucket: 'captura-lens-6d2a3.appspot.com',
    measurementId: 'G-MZ9N7GR61D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqTU95AGimpO2aL5v5JzKHpFsItuwexI',
    appId: '1:407480712095:android:a5d819f6f0382a663c5baa',
    messagingSenderId: '407480712095',
    projectId: 'captura-lens-6d2a3',
    storageBucket: 'captura-lens-6d2a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKzA91BKROiVwHepZLkOOK5N9hZD37uSc',
    appId: '1:407480712095:ios:e922adc2a2287d683c5baa',
    messagingSenderId: '407480712095',
    projectId: 'captura-lens-6d2a3',
    storageBucket: 'captura-lens-6d2a3.appspot.com',
    iosBundleId: 'com.example.capturaLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKzA91BKROiVwHepZLkOOK5N9hZD37uSc',
    appId: '1:407480712095:ios:9363676ffbe6c9c33c5baa',
    messagingSenderId: '407480712095',
    projectId: 'captura-lens-6d2a3',
    storageBucket: 'captura-lens-6d2a3.appspot.com',
    iosBundleId: 'com.example.capturaLens.RunnerTests',
  );
}
